name=csf_autogroup
service=whostmgr
url=/cgi/csf_autogroup/index.php
user=root
acls=all
displayname=CSF Auto-Group
entryurl=csf_autogroup/index.php
target=_self
searchtext=csf firewall autogroup ban subnet deny lfd güvenlik duvarı
icon=csf_autogroup.svg
